# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  Joint_1:
    has_position_limits: true
    min_position: -6.2831
    max_position: 6.2831
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  Joint_2:
    has_position_limits: true
    min_position: -6.2831
    max_position: 6.2831
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  Joint_3:
    has_position_limits: true
    min_position: -6.2831
    max_position: 6.2831
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  Joint_4:
    has_position_limits: true
    min_position: -6.2831
    max_position: 6.2831
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  Joint_5:
    has_position_limits: true
    min_position: -6.2831
    max_position: 6.2831
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 1.5
  Joint_6:
    has_position_limits: true
    min_position: -6.2831
    max_position: 6.2831
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 1.5